# Generated by Django 3.0.3 on 2020-02-05 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='alumncsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Middle_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Mailing_city', models.CharField(max_length=20)),
                ('Mailing_state', models.CharField(max_length=20)),
                ('USB_alumn', models.IntegerField()),
                ('Codigo_Alumn_USB', models.CharField(max_length=20)),
                ('Mailing_country', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=40, unique=True)),
                ('Mobile', models.CharField(max_length=20)),
                ('Cohorte', models.IntegerField()),
                ('Birthdate', models.DateTimeField()),
                ('Age', models.IntegerField()),
                ('Undergrad_degree', models.CharField(max_length=40)),
                ('Graduate_degree', models.CharField(max_length=40)),
                ('Carnet', models.IntegerField()),
                ('USB_undergrad_campus', models.CharField(max_length=30)),
                ('Graduate_campus', models.CharField(max_length=30)),
                ('Work_email', models.EmailField(max_length=40)),
                ('Workplace', models.CharField(max_length=20)),
                ('Donor', models.IntegerField()),
                ('Average_gift', models.FloatField()),
                ('Largest_gift', models.FloatField()),
                ('Smallest_gift', models.FloatField()),
                ('Total_gifts', models.FloatField()),
                ('Best_gift_year_total', models.FloatField()),
                ('Best_gift_year', models.IntegerField()),
                ('Social_networks', models.CharField(max_length=50)),
                ('Twitter_account', models.CharField(max_length=40)),
                ('Instagram_account', models.CharField(max_length=40)),
                ('First_gift_date', models.DateTimeField()),
                ('Last_gift_date', models.DateTimeField()),
                ('Total_number_of_gifts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Middle_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Mailing_city', models.CharField(max_length=20)),
                ('Mailing_state', models.CharField(max_length=20)),
                ('USB_alumn', models.IntegerField()),
                ('Codigo_Alumn_USB', models.CharField(max_length=20)),
                ('Mailing_country', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=40, unique=True)),
                ('Mobile', models.CharField(max_length=20)),
                ('Cohorte', models.IntegerField()),
                ('Birthdate', models.DateTimeField()),
                ('Age', models.IntegerField()),
                ('Undergrad_degree', models.CharField(max_length=40)),
                ('Graduate_degree', models.CharField(max_length=40)),
                ('Carnet', models.IntegerField()),
                ('USB_undergrad_campus', models.CharField(max_length=30)),
                ('Graduate_campus', models.CharField(max_length=30)),
                ('Work_email', models.EmailField(max_length=40)),
                ('Workplace', models.CharField(max_length=20)),
                ('Donor', models.IntegerField()),
                ('Social_networks', models.CharField(max_length=50)),
                ('Twitter_account', models.CharField(max_length=40)),
                ('Instagram_account', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=40, unique=True)),
                ('Average_gift', models.FloatField()),
                ('Largest_gift', models.FloatField()),
                ('Smallest_gift', models.FloatField()),
                ('Total_gifts', models.FloatField()),
                ('Best_gift_year_total', models.FloatField()),
                ('Best_gift_year', models.IntegerField()),
                ('First_gift_date', models.DateTimeField()),
                ('Last_gift_date', models.DateTimeField()),
                ('Total_number_of_gifts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Achievements')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
