# Generated by Django 3.0.3 on 2020-02-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumncsv',
            name='Birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='alumncsv',
            name='First_gift_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='alumncsv',
            name='Last_gift_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user_achievements',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user_stats',
            name='First_gift_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user_stats',
            name='Last_gift_date',
            field=models.DateField(),
        ),
    ]
