# Generated by Django 3.0.3 on 2020-02-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200205_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_information',
            name='Age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Carnet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Codigo_Alumn_USB',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Cohorte',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Donor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='First_name',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Graduate_campus',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Instagram_account',
            field=models.CharField(default='-', max_length=40),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Last_name',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Mailing_city',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Mailing_country',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Mailing_state',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Middle_name',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Mobile',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Social_networks',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Twitter_account',
            field=models.CharField(default='-', max_length=40),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='USB_alumn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='USB_undergrad_campus',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Workplace',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
