# Generated by Django 3.0.3 on 2020-02-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200227_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumncsv',
            name='Codigo_Alumn_USB',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='alumncsv',
            name='Email',
            field=models.EmailField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='alumncsv',
            name='First_name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='alumncsv',
            name='Graduate_degree',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='alumncsv',
            name='Instagram_account',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='alumncsv',
            name='Last_name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='alumncsv',
            name='Mailing_city',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='alumncsv',
            name='Mailing_country',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='alumncsv',
            name='Mailing_state',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='alumncsv',
            name='Middle_name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='alumncsv',
            name='Mobile',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='alumncsv',
            name='Twitter_account',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='alumncsv',
            name='Undergrad_degree',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='alumncsv',
            name='Work_email',
            field=models.EmailField(max_length=400),
        ),
        migrations.AlterField(
            model_name='alumncsv',
            name='Workplace',
            field=models.CharField(max_length=400),
        ),
    ]
