# Generated by Django 3.0.3 on 2020-02-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200227_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_information',
            name='Codigo_Alumn_USB',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='First_name',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Last_name',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Mailing_city',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Mailing_state',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Middle_name',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Mobile',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Workplace',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
