# Generated by Django 3.0.3 on 2020-02-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200227_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_information',
            name='Email',
            field=models.EmailField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Graduate_degree',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Instagram_account',
            field=models.CharField(default='-', max_length=60),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Twitter_account',
            field=models.CharField(default='-', max_length=60),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Work_email',
            field=models.EmailField(max_length=60),
        ),
    ]
