# Generated by Django 3.0.3 on 2020-02-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200228_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumncsv',
            name='Email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='Email',
            field=models.EmailField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='user_stats',
            name='Email',
            field=models.EmailField(max_length=60, unique=True),
        ),
    ]
