# Generated by Django 3.0.3 on 2020-03-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200228_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_stats',
            name='Best_gift_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_stats',
            name='First_gift_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user_stats',
            name='Last_gift_date',
            field=models.DateField(null=True),
        ),
    ]
