# Generated by Django 3.0.3 on 2020-03-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200305_0117'),
        ('accounts', '0018_auto_20200306_1200'),
    ]

    operations = [
    ]
