# Generated by Django 3.0.3 on 2020-03-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200317_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alumncsv',
        ),
    ]
