# Generated by Django 3.0.3 on 2020-03-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_delete_alumncsv'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='Picture',
            field=models.ImageField(default='../static/achiev_img/C.png', upload_to=''),
        ),
    ]
