# Generated by Django 3.0.3 on 2020-03-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200317_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='id',
        ),
        migrations.AlterField(
            model_name='achievements',
            name='Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
