# Generated by Django 3.0.3 on 2020-03-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20200317_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_achievements',
            name='Achievement',
        ),
        migrations.RemoveField(
            model_name='user_achievements',
            name='Owner',
        ),
    ]
