# Generated by Django 3.0.3 on 2020-03-17 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0026_auto_20200317_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_achievements',
            name='Achievement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Achievements'),
        ),
        migrations.AddField(
            model_name='user_achievements',
            name='Owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
