# Generated by Django 3.0.3 on 2020-03-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20200317_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_achievements',
            name='Owner',
        ),
    ]
