# Generated by Django 3.0.3 on 2020-03-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_user_achievements_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='Level',
            field=models.IntegerField(default=1),
        ),
    ]
