# Generated by Django 3.0.3 on 2020-03-18 18:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_achievements_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_achievements',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 3, 18, 18, 38, 6, 83497, tzinfo=utc)),
        ),
    ]
