# Generated by Django 3.0.3 on 2020-03-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('Page', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Title', models.CharField(default=' ', max_length=50)),
                ('Txt', models.CharField(default=' ', max_length=2000)),
            ],
        ),
    ]
