# Generated by Django 3.0.3 on 2020-03-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.ImageField(upload_to='static/prof_img/')),
            ],
        ),
    ]
