# Generated by Django 3.0.3 on 2020-03-20 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_information',
            name='Picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile_Picture'),
        ),
    ]
